apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
  links:
    - url: ${{"https://cdp-data-eu-west-1-123123123123.s3.eu-west-1.amazonaws.com/mesh/" + values.directory}}
      title: S3 directory
      icon: cloud
  tags:
    - outputport
    - S3
spec:
  type: outputport
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system: ${{values.dataproduct | dump}}