apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
  links:
    - url: ${{"https://" + values.cdp_environment +".s3.eu-west-1.amazonaws.com/mesh/" + values.domain + "/" + values.dataproduct + "/" + values.version + "/" + values.directory}}
      title: S3 Directory
      icon: cloud
  tags:
    - outputport
    - s3
  mesh:
    resourceType: raw
    technology: s3
    issueDate:
    startDate:
    processDescription:
    billingPolicy:
    securityPolicy:
    consumerPolicy:
    slo:
    intervalOfChange:
    timeliness:
    allow: [ ]
    owner: ${{values.owner | dump}}
    dependsOn: [ ]
spec:
  type: outputport
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system: ${{values.dataproduct | dump}}
  mesh:
    folder: ${{values.directory}}
    cdpEnvironment: ${{values.cdp_environment}}
